import * as fs from 'fs';
import {minify} from 'minify';

(async () => {
    const components = ['gui', 'joystick'];

    for (const component of components) {
        const name = component.toUpperCase();
        const htmlFile = await minifyHTML(`./src/${component}.html`);
        const cssFile = await minifyCSS(`./src/${component}.css`);

        fs.writeFileSync(`./src/${component}-template.ts`, `// Generated with 'minify'.
export const ${name}Styles: string = \`${cssFile}\`;
export const ${name}Template: string = \`${htmlFile}\`;
`);
    }
})();

function minifyHTML(path) {
    return minify(path, {
        html: {
            includeAutoGeneratedTags: true,
            collapseWhitespace: true,
            removeComments: true,
            removeOptionalTags: true,
            removeRedundantAttributes: true,
            removeScriptTypeAttributes: true,
            removeTagWhitespace: true,
            useShortDoctype: true
        }
    });
}

function minifyCSS(path) {
    return minify(path, {
        css: {

        }
    });
}
